### ISSUE TITLE
Sinon asserts no longer work

### ISSUE THREAD

**Issue by starmandeluxe** [TNG/sinon-helpers#87]
When using plain Sinon, asserts are a given must-have in order for unit testing to be useful:

```
var stub = sinon.stub();
// use the stub...
assert(stub.called); // should be true!
```

However this no longer works when doing this:

```
var MyStubConstructor = sh.getStubConstructor(MyConstructor)
// use the stub...
assert(MyStubConstructor.called); // should be true!
```

But `called` is no longer defined. I didn't see anything in the sinon-helpers documentation about asserts, so I am not sure how I am supposed to achieve this. If it is possible, I'd also like to know how to assert that the instance's methods were called as well (not just the constructor).

**Comment by starmandeluxe** [comment]
Thanks for the info. I tried `getInstancesArgs()` but it returned undefined, and I couldn't find any info on `sinon.stub().args`. However I was able to work around it by asserting not on the constructor, but instead whatever happens after I use the dependent class (such as console.log() of whatever my methods return). It certainly would be awesome to somehow check that my constructor's methods were called, but I guess it's not a dealbreaker at the moment.

**Comment by lukastaegert** [comment]
Hi, I created a workbook in runkit that demonstrates how to use both of them: https://runkit.com/lukastaegert/5b6156ee3c152000122514e5

**Comment by starmandeluxe** [comment]
Ok now I understand what you mean, and it makes sense that I didn't get anything returned from `getInstancesArgs()`, because the constructors I am using always take zero parameters, so checking this wouldn't be useful. What I really need as I mentioned is a way to see the methods were called on the constructor, so using your example something like this is desired:

```
class Test {
  blah(myString) {
    return 'blah: ' + myString;
  }
};

const MyConstructor = sh.getStubConstructor(Test);
var stub = sinon.stub(MyConstructor, "blah");

//*supply this to the function we are testing, inside which "blah" is called*

assert(stub.called);
```

**Comment by lukastaegert** [comment]
In that case, you are not actually interested in calls of the constructor but calls of the methods of the instances. Without sinon-helpers, you could do it like this:

```js
var stub = sinon.stub(Test.prototype, "blah");
/* do something */
assert(stub.called);
```

The disadvantage here, however, is that all instances share the same stub which means that you cannot determine if there were 5 instances of `Test` created on which `.blah` is called once or if there is a single instance on which `.blah` is called 5 times.

With sinon-helpers, you would do it like this:

```js
const MyConstructor = sh.getStubConstructor(Test);
/* do something */

// If you expect there was only a single instance of test created.
// This will throw an error if more than one instance was created:
assert(MyConstrutor.getInstance().blah.called);
```

So the stub is already created for you but you have to retrieve the instance to verify it. Here is another runkit example: https://runkit.com/lukastaegert/5b63e81b878b10001129e9a3

If there is more than one instance created, you can retrieve instances by their index (0 for the first created instance, 1 for the second etc.) to check the stubs.

```js
assert(MyConstrutor.getInstance(0).blah.called);
assert(!MyConstrutor.getInstance(1).blah.called);
```

**Comment by starmandeluxe** [comment]
That did the trick! Thanks a lot for clearing that up!
